### ISSUE TITLE
'\startbib' call not functioning properly

### ISSUE THREAD

**Issue by skylarscott** [UDRC/udrcTemplates#1]
'\startbib' command currently not working for me.  I will post solution if found.  

`CTE education through USTC programs significantly increases wages for students and as a result increase taxes collected by the state over time. 

\onecol
\startbib

<br/>
Beyer, Ashley "Talent Ready Utah" 17 Nov. 2017 KUTV. https://kutv.com/features/fresh-living/talent-ready-utah Sinclair Broadcast Group
`

**Comment by UDRC** [comment]
Issue corrected through re-download of the package.
